name = "KWNDeformation"
version = "0.1.0"
license = "MIT"
author = "test author"
maintainer = "example@place.com"
copyright = "2022 UoM"

[[ executable ]]
name="KWNDeformation"
source-dir="app"
main="KWN_with_deformation.f90"